variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  cache: &global_cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - condaenv
      - .cache/pip
    policy: pull

  image: continuumio/miniconda3:latest

  before_script:
    - apt-get update -q -y
    - apt-get install -y build-essential
    - conda config --set env_prompt '({name})'
    - conda install mamba -c conda-forge
    - mamba env update --prefix ./condaenv -f environment.yml
    - source activate ./condaenv

stages:
  - gather
  - preprocess
  - analyses
  - test

# Prepare the conda environment
prepare:
  stage: .pre
  script:
    - echo "Created the env"
  cache:
    <<: *global_cache
    # override the policy
    policy: pull-push

getRawData:
  stage: gather
  script:
    - echo "Getting raw data from database."
    - python scripts/00-getrawdata.py
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - data/raw/
    exclude:
      - data/**/.gitignore
    untracked: false
    expire_in: 1 week

preprocess:
  stage: preprocess
  script:
    - echo "Preprocessing Data."
    - python scripts/01-preprocessdata.py
    - python scripts/02-analysesample.py
  needs:
    - job: getRawData
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - data/
      - reports/
    exclude:
      - data/**/.gitignore
      - reports/**/.gitignore
      - reports/tests/
    untracked: false
    expire_in: 1 week

analysis:
  stage: analyses
  script:
    - python scripts/03-describedof.py
    - python scripts/04-performance.py
    - python scripts/05-pca.py
    - python scripts/06-analyzesynergy.py
    # more scripts here.
  needs:
    - job: preprocess
      artifacts: true
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - reports
    exclude:
      - reports/**/.gitignore
      - reports/tests/
    untracked: false
    expire_in: 1 week

testDummyData:
  stage: test
  script:
    - "pytest -v tests/test_modelcomparison.py::TestModelComparator"
  dependencies: []
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - reports/tests/
    exclude:
      - reports/**/.gitignore
    untracked: false
    expire_in: 1 week
  rules:
    - changes:
        - src/neuropsymodelcomparison/dataprocessing/*.py
  needs: [prepare]

trigger_job:
  stage: .post
  trigger:
    project: OlafHaag/thesis
