name: pm3
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - pip=20.2.*
  - python=3.8
  - setuptools
  - pandoc
  - pandocfilters
  - numpy
  - pandas
  - pandas-flavor
  - scipy
  - statsmodels
  - scikit-learn
  - pingouin>=3.8
  - plotly
  - python-kaleido
  - Matplotlib
  - Seaborn
  - graphviz
  - python-graphviz
  - mkl
  - mkl-service
  - theano
  - pymc3
  - arviz
  - psycopg2
  - sqlalchemy
  - pytest
  - pytest-cov
  - autopep8
  - jupyterlab
  - pip:
      - astroid
      - isort
      - lazy-object-proxy
      - mccabe
      - pylint
      - toml
      - wrapt
      - -e .
